SET @@sql_mode= '';
alter table `zt_user` add index idx_deleted_id(deleted,id);
alter table `zt_category` add index idx_dele_type_id(deleted,type,id);
alter table `zt_zt_im_message` add index idx_date(date);
alter table `zt_zt_im_conference` add index idx_cgid(cgid);
alter table `zt_zt_im_conferenceaction` add index idx_rid_date(rid,date);
alter table `zt_zt_im_client` add index idx_strategy_status_id(strategy,status,id);
alter table zt_action              ENGINE=INNODB;
alter table zt_block               ENGINE=INNODB;
alter table zt_category            ENGINE=INNODB;
alter table zt_config              ENGINE=INNODB;
alter table zt_cron                ENGINE=INNODB;
alter table zt_file                ENGINE=INNODB;
alter table zt_group               ENGINE=INNODB;
alter table zt_grouppriv           ENGINE=INNODB;
alter table zt_history             ENGINE=INNODB;
alter table zt_zt_im_chat             ENGINE=INNODB;
alter table zt_zt_im_chatuser         ENGINE=INNODB;
alter table zt_zt_im_client           ENGINE=INNODB;
alter table zt_zt_im_conference       ENGINE=INNODB;
alter table zt_zt_im_conferenceaction ENGINE=INNODB;
alter table zt_zt_im_message          ENGINE=INNODB;
alter table zt_zt_im_messagestatus    ENGINE=INNODB;
alter table zt_zt_im_queue            ENGINE=INNODB;
alter table zt_lang                ENGINE=INNODB;
alter table zt_sso                 ENGINE=INNODB;
alter table zt_user                ENGINE=INNODB;
alter table zt_usergroup           ENGINE=INNODB;
